/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "greatest.h"

bool_t
xdr_max (XDR *xdrs, max *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}
