/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.

 */

#include "greatest.h" 


void
greatest_1(char *host, int a, int b, int c)
{
	CLIENT *clnt;
	int  *result_1;
	max  maximum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GREATEST, GREATEST_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	maximum_1_arg.x=a;
	maximum_1_arg.y=b;
	maximum_1_arg.z=c;
	result_1 = maximum_1(&maximum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Result:%d", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host NUMBER NUMBER NUMBER\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	greatest_1 (host, atoi(argv[2]), atoi(argv[3]), atoi(argv[4]));
exit (0);
}
