/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "greatest.h"

int *
maximum_1_svc(max *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * Server code that returns the greatest number among three integers
	 */
	
	printf("maximum(%d, %d, %d)\n", argp->x, argp->y, argp->z);
	
	if (argp->x > argp->y)
	    {
		if ( argp->x > argp->z)
		{
		    printf("The first integer is the greatest among three \n");
		}
		else
		{
		    printf("The third integer is greatest among three \n");
		}
	    }
	    else if (argp->y > argp->z)
		printf("The second integer is the greatest among three \n");
	    else
		printf("The third integer is the greatest among three \n");

		//return &result;
}
