/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GREATEST_H_RPCGEN
#define _GREATEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct max {
	int x;
	int y;
	int z;
};
typedef struct max max;

#define GREATEST 0x2fffffff
#define GREATEST_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define MAXIMUM 1
extern  int * maximum_1(max *, CLIENT *);
extern  int * maximum_1_svc(max *, struct svc_req *);
extern int greatest_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MAXIMUM 1
extern  int * maximum_1();
extern  int * maximum_1_svc();
extern int greatest_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_max (XDR *, max*);

#else /* K&R C */
extern bool_t xdr_max ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GREATEST_H_RPCGEN */
