/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CASE_H_RPCGEN
#define _CASE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct upperCase {
	char str[50];
};
typedef struct upperCase upperCase;

#define UPPERCASE 0x2fffffff
#define UPPERCASE_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define UPPER 1
extern  char * upper_1(upperCase *, CLIENT *);
extern  char * upper_1_svc(upperCase *, struct svc_req *);
extern int uppercase_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UPPER 1
extern  char * upper_1();
extern  char * upper_1_svc();
extern int uppercase_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_upperCase (XDR *, upperCase*);

#else /* K&R C */
extern bool_t xdr_upperCase ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CASE_H_RPCGEN */
