/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "case.h"


void
uppercase_1(char *host)
{
	CLIENT *clnt;
	char  *result_1;
	upperCase  upper_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UPPERCASE, UPPERCASE_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	 
	result_1 = upper_1(&upper_1_arg, clnt);
	if (result_1 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Result:%c", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host STRING\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	uppercase_1 (host);
exit (0);
}
