/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "case.h"

char *
upper_1_svc(upperCase *argp, struct svc_req *rqstp)
{
	static char  result;

	/*
	 * Server code that converts a string to upperCase
	 */
	
	printf("upper(%s)\n", argp->str);
         for (int i = 0; argp->str[i]!='\0'; i++)
  	{
  		if(argp->str[i] >= 'a' && argp->str[i] <= 'z')
  		{
  			argp->str[i] = argp->str[i] -32;
		}
  	}

  	printf("\n The given String in Upper Case = %s", argp->str);


}
