/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRODUCT_H_RPCGEN
#define _PRODUCT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct product {
	float x;
	float y;
};
typedef struct product product;

#define PRODUCT 0x2fffffff
#define PRODUCT_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTIPLY 1
extern  float * multiply_1(product *, CLIENT *);
extern  float * multiply_1_svc(product *, struct svc_req *);
extern int product_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTIPLY 1
extern  float * multiply_1();
extern  float * multiply_1_svc();
extern int product_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_product (XDR *, product*);

#else /* K&R C */
extern bool_t xdr_product ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRODUCT_H_RPCGEN */
