/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/* Function generated to multiply to float numbers */
#include "product.h"

float *
multiply_1_svc(product *argp, struct svc_req *rqstp)
{
	static float  result;

	/* Server code for multiplying two float number */
	printf("multiply(%f, %f) is called\n", argp->x,argp->y);
	result = argp->x * argp->y;


	return &result;
}
